name: seno
description: Une application de paiement rapide
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  hugeicons: ^1.1.1
  supabase: ^2.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

dependency_overrides:
  characters: ^1.4.1
  material_color_utilities: ^0.13.0
  meta: ^1.17.0
  test_api: ^0.7.8

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/pattern.png
    - assets/images/seno-logo.png
    - assets/images/ios-icon.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path_ios: "assets/images/ios-icon.png"
  image_path: "assets/images/seno-logo.png"
  adaptive_icon_background: "#FDFE96"
  adaptive_icon_foreground: "assets/images/seno-logo.png"
  remove_alpha_ios: true
  android_adaptive_icon_foreground: "assets/images/seno-logo.png"
  android_adaptive_icon_background: "#FDFE96"
  adaptive_icon_padding: "10%"
  min_sdk_android: 21

